version: '3.8'


services:
 watch-service:
   image: ashutosh23k/yt-watch:lts
   build:
     context: ./watch_service # Path to the backend Dockerfile
   ports:
     - "8082:8082"


 upload-service:
   image: ashutosh23k/yt-upload:lts
   build:
     context: ./upload_service # Path to the backend Dockerfile
   ports:
     - "8080:8080"


 transcoder-service:
   image: ashutosh23k/yt-transcoder:lts
   build:
     context: ./transcoder_service # Path to the backend Dockerfile
   ports:
     - "8000:8000" 


 yt-client:
   image: ashutosh23k/yt-client:lts
   build:
     context: ./client # Path to the frontend Dockerfile
   ports:
     - "3000:3000"
   depends_on:
     - watch-service # Wait for backend service to be ready before starting frontend
