import { Inter } from "next/font/google";
import "./globals.css";
import SessionProviderAuth from "./_components/sessionProviderAuth";
import NavBar from "./_components/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <SessionProviderAuth>
        <body className={inter.className}>
          <NavBar />
          {children}
        </body>
      </SessionProviderAuth>
    </html>
  );
}
